# Generated by Django 4.1.2 on 2022-10-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("product_no", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("random", "Random"),
                            ("fashion", "Fashion"),
                            ("electronics", "Electronics"),
                            ("furniture", "Furniture"),
                            ("grocery", "Grocery"),
                            ("computers", "Computers"),
                            ("books and literature", "Books & Literature"),
                        ],
                        default="random",
                        max_length=255,
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="")),
                ("quantity", models.IntegerField(blank=True, default=1)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "product_no")},
            },
        ),
    ]
