# Generated by Django 4.1.2 on 2023-01-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
