# Generated by Django 4.1.2 on 2022-12-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
