# Generated by Django 4.1.2 on 2022-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_productimage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
